#spring.application.name=bsgl
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.name=signagedb
#spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#server.port=8080
server:
  port: 8484
spring:
  resources:
    chain:
      cache: true
    static-locations: classpath:/static/**
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
  application:
    name: bsgl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.229.4.16:3306/signage?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: dcom
    password: Dcom123456
    hikari:
      max-lifetime: 500000
      minimum-idle: 10
      maximum-pool-size: 100
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
